from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import asdict
from datetime import datetime, timezone

from .models import Digest, GitHubItem


def render_digest(digest: Digest) -> str:
    lines = [
        f"# Maintainer Digest - {digest.repo}",
        "",
        f"Generated: {format_dt(digest.generated_at)}",
        f"Window: last {digest.days} days",
        f"Stale threshold: {digest.stale_days} days",
        "",
        "## Snapshot",
        "",
        f"- Needs triage: {len(digest.needs_triage)}",
        f"- Pull requests waiting review: {len(digest.waiting_review)}",
        f"- Stale open threads: {len(digest.stale_threads)}",
        f"- Recently closed: {len(digest.recently_closed)}",
        "",
    ]
    add_section(lines, "Needs Triage", digest.needs_triage)
    add_section(lines, "Pull Requests Waiting Review", digest.waiting_review)
    add_section(lines, "Stale Open Threads", digest.stale_threads)
    add_section(lines, "Recently Closed", digest.recently_closed)
    add_section(lines, "Recent Activity", digest.recent_activity)
    lines.extend(
        [
            "",
            "---",
            "",
            "Generated by Maintainer Cron Kit. Review before posting publicly.",
            "",
        ]
    )
    return "\n".join(lines)


def render_release_notes(repo: str, items: list[GitHubItem], days: int) -> str:
    pull_requests = [
        item for item in items if item.is_pull_request and item.state == "closed"
    ]
    grouped: dict[str, list[GitHubItem]] = defaultdict(list)
    for item in pull_requests:
        grouped[group_for(item)].append(item)

    lines = [
        f"# Release Notes Draft - {repo}",
        "",
        f"Source window: recently updated closed pull requests from the last {days} days.",
        "",
    ]
    if not pull_requests:
        lines.extend(["No recently closed pull requests found.", ""])
        return "\n".join(lines)

    for group in ["Features", "Fixes", "Documentation", "Maintenance", "Other"]:
        group_items = grouped.get(group, [])
        if not group_items:
            continue
        lines.extend([f"## {group}", ""])
        for item in sorted(group_items, key=lambda pr: pr.number):
            lines.append(f"- {item.title} (#{item.number})")
        lines.append("")
    lines.extend(["---", "", "Generated by Maintainer Cron Kit. Edit before release.", ""])
    return "\n".join(lines)


def add_section(lines: list[str], title: str, items: tuple[GitHubItem, ...]) -> None:
    lines.extend([f"## {title}", ""])
    if not items:
        lines.extend(["None.", ""])
        return
    for item in items:
        kind = "PR" if item.is_pull_request else "Issue"
        labels = f" labels: {', '.join(item.labels)}" if item.labels else ""
        lines.append(
            f"- [{kind} #{item.number}]({item.html_url}) {item.title} "
            f"- @{item.author}, updated {format_dt(item.updated_at)}{labels}"
        )
    lines.append("")


def group_for(item: GitHubItem) -> str:
    text = f"{item.title} {' '.join(item.labels)}".lower()
    if any(token in text for token in ["feat", "feature", "add"]):
        return "Features"
    if any(token in text for token in ["fix", "bug", "patch"]):
        return "Fixes"
    if any(token in text for token in ["doc", "readme", "guide"]):
        return "Documentation"
    if any(token in text for token in ["chore", "ci", "refactor", "test", "deps"]):
        return "Maintenance"
    return "Other"


def format_dt(value) -> str:
    return value.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def json_datetime(value: datetime) -> str:
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def render_digest_json(digest: Digest) -> str:
    return json.dumps(asdict(digest), default=json_datetime, ensure_ascii=False, indent=2)


def render_release_notes_json(repo: str, items: list[GitHubItem], days: int) -> str:
    groups: dict[str, list[dict]] = {}
    for item in sorted(items, key=lambda item: item.number):
        if item.is_pull_request and item.state == "closed":
            groups.setdefault(group_for(item), []).append(asdict(item))
    return json.dumps(
        {"repo": repo, "days": days, "groups": groups},
        default=json_datetime, ensure_ascii=False, indent=2,
    )
